*
*  Source machine generated by GadToolsBox V2.0
*  which is (c) Copyright 1991-1993 Jaba Development
*
*  GUI Designed by : JEO
*

    include 'exec/types.i'
    include 'intuition/intuition.i'
    include 'intuition/classes.i'
    include 'libraries/gadtools.i'

	XDEF	Project0NewMenu0

Project0NewMenu0:
    DC.B    NM_TITLE,0
    DC.L    Project0MName0
    DC.L    0
    DC.W    0
    DC.L    0,0

Project0NewMenu1:
    DC.B    NM_ITEM,0
    DC.L    Project0MName1
    DC.L    Project0MComm1
    DC.W    CHECKIT!MENUTOGGLE
    DC.L    0,0

Project0NewMenu2:
    DC.B    NM_ITEM,0
    DC.L    Project0MName2
    DC.L    Project0MComm2
    DC.W    0
    DC.L    0,0

Project0NewMenu3:
    DC.B    NM_ITEM,0
    DC.L    Project0MName3
    DC.L    Project0MComm3
    DC.W    0
    DC.L    0,0

Project0NewMenu4:
    DC.B    NM_ITEM,0
    DC.L    Project0MName4
    DC.L    Project0MComm4
    DC.W    0
    DC.L    0,0

Project0NewMenu5:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

Project0NewMenu6:
    DC.B    NM_ITEM,0
    DC.L    Project0MName6
    DC.L    Project0MComm6
    DC.W    0
    DC.L    0,0

Project0NewMenu7:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

Project0NewMenu8:
    DC.B    NM_ITEM,0
    DC.L    Project0MName8
    DC.L    Project0MComm8
    DC.W    0
    DC.L    0,0

Project0NewMenu9:
    DC.B    NM_ITEM,0
    DC.L    Project0MName9
    DC.L    Project0MComm9
    DC.W    NM_ITEMDISABLED
    DC.L    0,0

Project0NewMenu10:
    DC.B    NM_ITEM,0
    DC.L    Project0MName10
    DC.L    Project0MComm10
    DC.W    NM_ITEMDISABLED
    DC.L    0,0

Project0NewMenu11:
    DC.B    NM_TITLE,0
    DC.L    Project0MName11
    DC.L    0
    DC.W    0
    DC.L    0,0

Project0NewMenu12:
    DC.B    NM_ITEM,0
    DC.L    Project0MName12
    DC.L    Project0MComm12
    DC.W    0
    DC.L    0,0

Project0NewMenu13:
    DC.B    NM_ITEM,0
    DC.L    Project0MName13
    DC.L    Project0MComm13
    DC.W    0
    DC.L    0,0

Project0NewMenu14:
    DC.B    NM_ITEM,0
    DC.L    Project0MName14
    DC.L    Project0MComm14
    DC.W    0
    DC.L    0,0

Project0NewMenu15:
    DC.B    NM_ITEM,0
    DC.L    Project0MName15
    DC.L    Project0MComm15
    DC.W    0
    DC.L    0,0

Project0NewMenu16:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

Project0NewMenu17:
    DC.B    NM_ITEM,0
    DC.L    Project0MName17
    DC.L    Project0MComm17
    DC.W    0
    DC.L    0,0

    DC.B    NM_END,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0

Project0MName0:
    DC.B    'This node',0

Project0MName1:
    DC.B    'Chat',0

Project0MComm1:
    DC.B    'S',0

Project0MName2:
    DC.B    'Show user',0

Project0MComm2:
    DC.B    'U',0

Project0MName3:
    DC.B    'Eject user',0

Project0MComm3:
    DC.B    'E',0

Project0MName4:
    DC.B    'Kill user',0

Project0MComm4:
    DC.B    'K',0

Project0MName6:
    DC.B    'Zoom Window',0

Project0MComm6:
    DC.B    'Z',0

Project0MName8:
    DC.B    'Hide node',0

Project0MComm8:
    DC.B    'H',0

Project0MName9:
    DC.B    'Shut down',0

Project0MComm9:
    DC.B    'D',0

Project0MName10:
    DC.B    'Shut down busy',0

Project0MComm10:
    DC.B    'B',0

Project0MName11:
    DC.B    'User',0

Project0MName12:
    DC.B    'Add 5 min',0

Project0MComm12:
    DC.B    '+',0

Project0MName13:
    DC.B    'Sub 5 min',0

Project0MComm13:
    DC.B    '-',0

Project0MName14:
    DC.B    'Add 5 f min',0

Project0MComm14:
    DC.B    '>',0

Project0MName15:
    DC.B    'Sub 5 f min',0

Project0MComm15:
    DC.B    '<',0

Project0MName17:
    DC.B    'Tmp sysop',0

Project0MComm17:
    DC.B    'T',0

	END
