*
*  Source machine generated by GadToolsBox V2.0b
*  which is (c) Copyright 1991-1993 Jaba Development
*
*  GUI Designed by : JEO
*

    include 'exec/types.i'
    include 'intuition/intuition.i'
    include 'intuition/classes.i'
    include 'intuition/classusr.i'
    include 'intuition/imageclass.i'
    include 'intuition/gadgetclass.i'
    include 'libraries/gadtools.i'
    include 'libraries/gadtools_lib.i'
    include 'libraries/intuition_lib.i'
    include 'libraries/exec_lib.i'
    include 'graphics/displayinfo.i'
    include 'graphics/gfxbase.i'

	XREF	exebase
	XREF	intbase
	XREF	gfxbase
	XREF	gadbase
	XREF	nodelist

_SysBase	equ	exebase
_IntuitionBase	equ	intbase
_GfxBase	equ	gfxbase
_GadToolsBase	equ	gadbase

	XDEF	OpenABBSAppWindowWindow
	XDEF	CloseABBSAppWindowWindow
	XDEF	SetupScreen
	XDEF	CloseDownScreen
	XDEF	ABBSAppWindowRender
	XDEF	ABBSAppWindowWnd
	XDEF	ABBSAppWindowGadgets
	XDEF	ABBSAppWindowMenus
	XDEF	ABBSAppWindowLeft
	XDEF	ABBSAppWindowTop

	IFND GT_Underscore
GT_Underscore	EQU	GT_TagBase+64	; ti_Data points to the symbol
	ENDC

GD_ListViewGadget                      EQU    0
GD_ShowGadget                          EQU    1
GD_HideGadget                          EQU    2
GD_ChatGadget                          EQU    3
GD_OffHook                             EQU    4
GD_EjectGadget                         EQU    5
GD_killgadget                          EQU    6
GD_TmpSysopGadget                      EQU    7
GD_ShowuserGadget                      EQU    8
GD_shutdownGadget                      EQU    9
GD_foo2                                EQU    10
GD_CloseABBSGadget                     EQU    11
GD_Reopen_node                         EQU    12
GD_EjectAll                            EQU    13
GD_Init_modem                          EQU    14
GD_Release_port                        EQU    15
GD_Win_size                            EQU    16

Y1 = 70
Y2 = Y1+11

ABBSAppWindow_CNT    EQU    17
Scr:
    DC.L    0
VisualInfo:
    DC.L    0
PubScreenName:
    DC.L    0
ABBSAppWindowWnd:
    DC.L    0
ABBSAppWindowGList:
    DC.L    0
ABBSAppWindowMenus:
    DC.L    0
MTags0:
    DC.L    GTMN_FrontPen,1,TAG_DONE
MTags1:
    DC.L    TAG_DONE
ABBSAppWindowGadgets:
    DCB.L    17,0
BufNewGad:
    DC.W    0,0,0,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0,0
BufIText:
    DC.B    0,0,0,0
    DC.W    0,0
    DC.L    0,0,0
TD:
    DC.L    TAG_DONE
NR:
    DC.L    GT_VisualInfo,$00000000,TAG_DONE
IR:
    DC.L    GT_VisualInfo,$00000000,GTBB_Recessed,1,TAG_DONE
ABBSAppWindowLeft:
    DC.W    0
ABBSAppWindowTop:
    DC.W    11
ABBSAppWindowWidth:
    DC.W    630
ABBSAppWindowHeight:
    DC.W    Y1+26
Font:
    DC.L    0
FontX:
    DC.W    0
FontY:
    DC.W    0
OffX:
    DC.W    0
OffY:
    DC.W    0
Attr:
    DC.L    0
    DC.W    0
    DC.B    0,0
TopazName:
    DC.B    'topaz.font',0
    CNOP    0,2

ABBSAppWindowGTypes:
    DC.W    LISTVIEW_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    BUTTON_KIND
    DC.W    CYCLE_KIND

ABBSAppWindowNGads:
    DC.W    4,13,623,Y1-12
    DC.L    ListViewGadgetText,0
    DC.W    GD_ListViewGadget
    DC.L    0,0,0
    DC.W    9,Y1,44,11
    DC.L    ShowGadgetText,0
    DC.W    GD_ShowGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    9,Y2,44,11
    DC.L    HideGadgetText,0
    DC.W    GD_HideGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    55,Y1,44,11
    DC.L    ChatGadgetText,0
    DC.W    GD_ChatGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    101,Y2,84,11
    DC.L    OffHookText,0
    DC.W    GD_OffHook
    DC.L    PLACETEXT_IN,0,0
    DC.W    277,Y1,88,11
    DC.L    EjectGadgetText,0
    DC.W    GD_EjectGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    55,Y2,44,11
    DC.L    killgadgetText,0
    DC.W    GD_killgadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    101,Y1,84,11
    DC.L    TmpSysopGadgetText,0
    DC.W    GD_TmpSysopGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    187,Y1,88,11
    DC.L    ShowuserGadgetText,0
    DC.W    GD_ShowuserGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    492,Y1,76,11
    DC.L    shutdownGadgetText,0
    DC.W    GD_shutdownGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    187,Y2,88,11
    DC.L    foo2Text,0
    DC.W    GD_foo2
    DC.L    PLACETEXT_IN,0,0
    DC.W    570,Y2,50,11
    DC.L    CloseABBSGadgetText,0
    DC.W    GD_CloseABBSGadget
    DC.L    PLACETEXT_IN,0,0
    DC.W    492,Y2,76,11
    DC.L    Reopen_nodeText,0
    DC.W    GD_Reopen_node
    DC.L    PLACETEXT_IN,0,0
    DC.W    277,Y2,88,11
    DC.L    EjectAllText,0
    DC.W    GD_EjectAll
    DC.L    PLACETEXT_IN,0,0
    DC.W    367,Y1,123,11
    DC.L    Init_modemText,0
    DC.W    GD_Init_modem
    DC.L    PLACETEXT_IN,0,0
    DC.W    367,Y2,123,11
    DC.L    Release_portText,0
    DC.W    GD_Release_port
    DC.L    PLACETEXT_IN,0,0
    DC.W    563,1,63,11
    DC.L    Win_sizeText,0
    DC.W    GD_Win_size
    DC.L    0,0,0

ABBSAppWindowGTags:
    DC.L    GTLV_ShowSelected,0
    DC.l    GTLV_Labels,nodelist
    DC.L    LAYOUTA_Spacing,2
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    GA_Disabled,1
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    GA_Disabled,1
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    GA_Disabled,1
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GA_Disabled,1
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE
    DC.L    GTCY_Labels,Win_sizeLabels
    DC.L    GTCY_Active,1
    DC.L    GT_Underscore,'_'
    DC.L    TAG_DONE


ListViewGadgetText:
    DC.B    '',0

ShowGadgetText:
    DC.B    '_Show',0

HideGadgetText:
    DC.B    '_Hide',0

ChatGadgetText:
    DC.B    'Chat',0

OffHookText:
    DC.B    '_Off Hook',0

EjectGadgetText:
    DC.B    '_Eject user',0

killgadgetText:
    DC.B    'Kill',0

TmpSysopGadgetText:
    DC.B    'TmpSysop',0

ShowuserGadgetText:
    DC.B    'Sh_ow user',0

shutdownGadgetText:
    DC.B    'Sh_utDown',0

foo2Text:
    DC.B    'Edit User',0

CloseABBSGadgetText:
    DC.B    '_Quit',0

Reopen_nodeText:
    DC.B    '_ReOpen',0

EjectAllText:
    DC.B    'Eject _ALL',0

Init_modemText:
    DC.B    '_Init Modem',0

Release_portText:
    DC.B    'Re_lease Serial',0

Win_sizeText:
    DC.B    '',0

    CNOP    0,2

Win_sizeLabels:
    DC.L    Win_sizeLab0
    DC.L    Win_sizeLab1
    DC.L    0

Win_sizeLab0:    DC.B    'Hide',0
Win_sizeLab1:    DC.B    'Show',0

    CNOP    0,2

	IFND	WFLG_NEWLOOKMENUS
WFLG_NEWLOOKMENUS	EQU $00200000	; window has NewLook menus
	ENDC

ABBSAppWindowWindowTags:
ABBSAppWindowL:
    DC.L    WA_Left,0
ABBSAppWindowT:
    DC.L    WA_Top,0
ABBSAppWindowW:
    DC.L    WA_Width,0
ABBSAppWindowH:
    DC.L    WA_Height,0
    DC.L    WA_IDCMP,LISTVIEWIDCMP!BUTTONIDCMP!CYCLEIDCMP!IDCMP_MENUPICK!IDCMP_CLOSEWINDOW!IDCMP_REFRESHWINDOW|IDCMP_SIZEVERIFY|IDCMP_VANILLAKEY|IDCMP_NEWSIZE
    DC.L    WA_Flags,WFLG_DRAGBAR!WFLG_DEPTHGADGET!WFLG_CLOSEGADGET!WFLG_SMART_REFRESH|WFLG_NEWLOOKMENUS
ABBSAppWindowWG:
    DC.L    WA_Gadgets,0
    DC.L    WA_Title,ABBSAppWindowWTitle
    DC.L    WA_ScreenTitle,ABBSAppWindowSTitle
ABBSAppWindowSC:
    DC.L    WA_PubScreen,0
    DC.L    TAG_DONE

ABBSAppWindowWTitle:
    DC.B    'ABBS II - Copyright © 1997-2000 Jan Erik Olausen',0
    CNOP    0,2

ABBSAppWindowSTitle:
    DC.B    'ABBS II - Copyright © 1997-2000 Jan Erik Olausen',0
    CNOP    0,2

ABBSAppWindowText0:
    DC.B    1,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    22,7
    DC.L    0
    DC.L    ABBSAppWindowIText0
    DC.L    0

ABBSAppWindowText1:
    DC.B    1,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    65,7
    DC.L    0
    DC.L    ABBSAppWindowIText1
    DC.L    0

ABBSAppWindowText2:
    DC.B    1,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    127,7
    DC.L    0
    DC.L    ABBSAppWindowIText2
    DC.L    0

ABBSAppWindowText3:
    DC.B    1,0
    DC.B    RP_JAM1
    DC.B    0
    DC.W    319,7
    DC.L    0
    DC.L    ABBSAppWindowIText3
    DC.L    0

ABBSAppWindow_TNUM EQU 4

ABBSAppWindowIText0:
    DC.B    'Node',0

ABBSAppWindowIText1:
    DC.B    'Speed',0

ABBSAppWindowIText2:
    DC.B    'Status',0

ABBSAppWindowIText3:
    DC.B    'Caller',0

    CNOP    0,2

ABBSAppWindowNewMenu0:
    DC.B    NM_TITLE,0
    DC.L    ABBSAppWindowMName0
    DC.L    0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu1:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName1
    DC.L    ABBSAppWindowMComm1
    DC.W    NM_ITEMDISABLED
    DC.L    0,0

ABBSAppWindowNewMenu2:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu3:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName3
    DC.L    ABBSAppWindowMComm3
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu4:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu5:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName5
    DC.L    ABBSAppWindowMComm5
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu6:
    DC.B    NM_TITLE,0
    DC.L    ABBSAppWindowMName6
    DC.L    0
    DC.W    NM_MENUDISABLED!CHECKIT
    DC.L    0,0

ABBSAppWindowNewMenu7:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName7
    DC.L    ABBSAppWindowMComm7
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu8:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName8
    DC.L    ABBSAppWindowMComm8
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu9:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu10:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName10
    DC.L    ABBSAppWindowMComm10
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu11:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu12:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName12
    DC.L    ABBSAppWindowMComm12
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu13:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName13
    DC.L    ABBSAppWindowMComm13
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu14:
    DC.B    NM_TITLE,0
    DC.L    ABBSAppWindowMName14
    DC.L    0
    DC.W    NM_MENUDISABLED!CHECKIT
    DC.L    0,0

ABBSAppWindowNewMenu15:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName15
    DC.L    0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu16:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName16
    DC.L    0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu17:
    DC.B    NM_ITEM,0
    DC.L    NM_BARLABEL,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu18:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName18
    DC.L    0
    DC.W    0
    DC.L    0,0

ABBSAppWindowNewMenu19:
    DC.B    NM_ITEM,0
    DC.L    ABBSAppWindowMName19
    DC.L    0
    DC.W    0
    DC.L    0,0

    DC.B    NM_END,0
    DC.L    0,0
    DC.W    0
    DC.L    0,0

ABBSAppWindowMName0:
    DC.B    'Project',0

ABBSAppWindowMName1:
    DC.B    'About',0

ABBSAppWindowMComm1:
    DC.B    'A',0

ABBSAppWindowMName3:
    DC.B    'Iconify',0

ABBSAppWindowMComm3:
    DC.B    'I',0

ABBSAppWindowMName5:
    DC.B    'ShutDown',0

ABBSAppWindowMComm5:
    DC.B    'Q',0

ABBSAppWindowMName6:
    DC.B    'Misc',0

ABBSAppWindowMName7:
    DC.B    'Eject User',0

ABBSAppWindowMComm7:
    DC.B    'E',0

ABBSAppWindowMName8:
    DC.B    'Kill User',0

ABBSAppWindowMComm8:
    DC.B    'K',0

ABBSAppWindowMName10:
    DC.B    'Chat',0

ABBSAppWindowMComm10:
    DC.B    'C',0

ABBSAppWindowMName12:
    DC.B    'Tmp Sysop',0

ABBSAppWindowMComm12:
    DC.B    'T',0

ABBSAppWindowMName13:
    DC.B    'Modify User',0

ABBSAppWindowMComm13:
    DC.B    'M',0

ABBSAppWindowMName14:
    DC.B    'Time',0

ABBSAppWindowMName15:
    DC.B    'Add 5min',0

ABBSAppWindowMName16:
    DC.B    'Sub 5min',0

ABBSAppWindowMName18:
    DC.B    'Add 5min FT',0

ABBSAppWindowMName19:
    DC.B    'Sub 5min FT',0

    CNOP    0,2

ComputeX:
    move.l  d1,-(sp)
    move.w  FontX,d1
    bra.s   ComputeItX
ComputeY:
    move.l  d1,-(sp)
    move.w  FontY,d1
    mulu    d1,d0
    addq.w  #4,d0
    divu    #8,d0
    move.l  (sp)+,d1
    rts

ComputeItX:
    mulu    d1,d0
    addq.w  #4,d0
    divu    #8,d0
    move.l  (sp)+,d1
    rts

ComputeFont:
    lea.l   Attr,a0
    move.l  a0,Font
    move.l  Scr,a1
    lea.l   sc_RastPort(a1),a1
    move.l  rp_Font(a1),a1
    move.l  LN_NAME(a1),ta_Name(a0)
    move.w  tf_YSize(a1),ta_YSize(a0)
    move.w  tf_XSize(a1),FontX
    move.w  tf_YSize(a1),FontY
    move.l  Scr,a0
    move.b  sc_WBorLeft(a0),d0
    ext.w   d0
    move.w  d0,OffX
    move.l  sc_Font(a0),a1
    move.w  ta_YSize(a1),d0
    addq.w  #1,d0
    move.b  sc_WBorTop(a0),d1
    ext.w   d1
    add.w   d1,d0
    move.w  d0,OffY
    tst.w   d2
    beq.s   CompDone
    tst.w   d3
    beq.s   CompDone
    move.w  d2,d0
    jsr     ComputeX
    add.w   OffX,d0
    move.b  sc_WBorRight(a0),d1
    ext.w   d1
    add.w   d1,d0
    cmp.w   sc_Width(a0),d0
    bhi.s   UseTopaz
    move.w  d3,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.b  sc_WBorBottom(a0),d1
    ext.w   d1
    add.w   d1,d0
    cmp.w   sc_Height(a0),d0
    bhi.s   UseTopaz
CompDone:
    rts
UseTopaz:
    move.l  Font,a0
    move.l  #TopazName,ta_Name(a0)
    move.w  #8,FontY
    move.w  #8,FontX
    move.w  #8,ta_YSize(a0)
    rts

SetupScreen
    movem.l d1-d3/a0-a2/a6,-(sp)
    move.l  _IntuitionBase,a6
    move.l  PubScreenName,a0
    jsr     _LVOLockPubScreen(a6)
    move.l  d0,Scr
    tst.l   d0
    beq     SError
    moveq   #0,d2
    moveq   #0,d3
    jsr     ComputeFont
    move.l  Scr,a0
    move.l  _GadToolsBase,a6
    lea.l   TD,a1
    jsr     _LVOGetVisualInfoA(a6)
    move.l  d0,VisualInfo
    tst.l   d0
    beq     VError
    moveq   #0,d0
SDone:
    movem.l (sp)+,d1-d3/a0-a2/a6
    rts
SError:
    moveq   #1,d0
    bra.s   SDone
VError:
    moveq   #2,d0
    bra.s   SDone

CloseDownScreen:
    movem.l d0-d1/a0-a1/a6,-(sp)
    move.l  _GadToolsBase,a6
    move.l  VisualInfo,a0
    cmpa.l  #0,a0
    beq.s   NoVis
    jsr     _LVOFreeVisualInfo(a6)
    move.l  #0,VisualInfo
NoVis:
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    move.l  Scr,a1
    cmpa.l  #0,a1
    beq.s   NoScr
    jsr     _LVOUnlockPubScreen(a6)
    move.l  #0,Scr
NoScr:
    movem.l (sp)+,d0-d1/a0-a1/a6
    rts

ABBSAppWindowRender:
    movem.l d0-d5/a0-a2/a6,-(sp)
    move.l  ABBSAppWindowWnd,a0
    move.w  ABBSAppWindowWidth,d2
    move.l  ABBSAppWindowHeight,d3
    jsr     ComputeFont
    move.l  VisualInfo,NR+4
    move.l  VisualInfo,IR+4
    move.l  _GadToolsBase,a6
    move.l  ABBSAppWindowWnd,a0
    move.l  wd_RPort(a0),a2
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #1,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #37,d0
    jsr     ComputeX
    move.l  d0,d2
    move.l  #11,d0
    jsr     ComputeY
    move.l  d0,d3
    move.l  #3,d0
    jsr     ComputeX
    add.w   OffX,d0
    jsr     _LVODrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #1,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #48,d0
    jsr     ComputeX
    move.l  d0,d2
    move.l  #11,d0
    jsr     ComputeY
    move.l  d0,d3
    move.l  #42,d0
    jsr     ComputeX
    add.w   OffX,d0
    jsr     _LVODrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #1,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #198,d0
    jsr     ComputeX
    move.l  d0,d2
    move.l  #11,d0
    jsr     ComputeY
    move.l  d0,d3
    move.l  #92,d0
    jsr     ComputeX
    add.w   OffX,d0
    jsr     _LVODrawBevelBoxA(a6)
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #1,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #269,d0
    jsr     ComputeX
    move.l  d0,d2
    move.l  #11,d0
    jsr     ComputeY
    move.l  d0,d3
    move.l  #292,d0
    jsr     ComputeX
    add.w   OffX,d0
    jsr     _LVODrawBevelBoxA(a6) ; Caller
    move.l  a2,a0
    lea.l   IR,a1
    move.l  #Y1-2,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  d0,d1
    move.l  #622,d0
    jsr     ComputeX
    move.l  d0,d2
    move.l  #26,d0
    jsr     ComputeY
    move.l  d0,d3
    move.l  #4,d0
    jsr     ComputeX
    add.w   OffX,d0
    jsr     _LVODrawBevelBoxA(a6)	; Gadgets
    moveq   #0,d3
    lea.l   ABBSAppWindowText0,a2
ABBSAppWindowTLoop:
    move.l  _SysBase,a6
    lea.l   BufIText,a1
    move.l  a2,a0
    move.l  d3,d0
    mulu    #it_SIZEOF,d0
    add.l   d0,a0
    moveq   #it_SIZEOF,d0
    jsr     _LVOCopyMem(a6)
    lea.l   BufIText,a0
    move.l  _IntuitionBase,a6
    move.l  Font,it_ITextFont(a0)
    jsr     _LVOIntuiTextLength(a6)
    asr.l   #1,d0
    move.l  d0,-(sp)
    lea.l   BufIText,a0
    move.w  it_LeftEdge(a0),d0
    jsr     ComputeX
    add.w   OffX,d0
    ext.l   d0
    sub.l   (sp)+,d0
    move.w  d0,it_LeftEdge(a0)
    move.w  it_TopEdge(a0),d0
    jsr     ComputeY
    add.w   OffY,d0
    move.l  Font,a1
    move.w  ta_YSize(a1),d1
    asr.w   #1,d1
    sub.w   d1,d0
    move.w  d0,it_TopEdge(a0)
    move.l  a0,a1
    move.l  ABBSAppWindowWnd,a0
    move.l  wd_RPort(a0),a0
    moveq   #0,d0
    moveq   #0,d1
    jsr     _LVOPrintIText(a6)
    addq.l  #1,d3
    cmp.l   #ABBSAppWindow_TNUM,d3
    bmi     ABBSAppWindowTLoop
    movem.l (sp)+,d0-d5/a0-a2/a6
    rts

OpenABBSAppWindowWindow:
    movem.l d1-d4/a0-a4/a6,-(sp)
    move.l  Scr,a0
    moveq   #0,d3
    moveq   #0,d2
    move.w  ABBSAppWindowWidth,d2
    move.w  ABBSAppWindowHeight,d3
    jsr     ComputeFont
    move.l  Scr,a0
    move.l  d2,d0
    jsr     ComputeX
    move.l  d0,d4
    move.w  ABBSAppWindowLeft,d2
    add.w   d2,d0
    add.w   OffX,d0
    move.b  sc_WBorRight(a0),d1
    ext.w   d1
    add.w   d1,d0
    cmp.w   sc_Width(a0),d0
    bls.s   ABBSAppWindowWOk
    move.w  sc_Width(a0),d0
    sub.w   d4,d0
    move.w  d0,d2
ABBSAppWindowWOk:
    move.l  d3,d0
    jsr     ComputeY
    move.l  d0,d4
    move.w  ABBSAppWindowTop,d3
    add.w   d3,d0
    add.w   OffY,d0
    move.b  sc_WBorBottom(a0),d1
    ext.w   d1
    add.w   d1,d0
    cmp.w   sc_Height(a0),d0
    bls.s   ABBSAppWindowHOk
    move.w  sc_Height(a0),d0
    sub.w   d4,d0
    move.w  d0,d3
ABBSAppWindowHOk:
    move.l  _GadToolsBase,a6
    lea.l   ABBSAppWindowGList,a0
    jsr     _LVOCreateContext(a6)
    move.l  d0,a3
    tst.l   d0
    beq     ABBSAppWindowCError
    movem.w d2-d3,-(sp)
    moveq   #0,d3
    lea.l   ABBSAppWindowGTags,a4
ABBSAppWindowGL:
    move.l  _SysBase,a6
    lea.l   ABBSAppWindowNGads,a0
    move.l  d3,d0
    mulu    #gng_SIZEOF,d0
    add.l   d0,a0
    lea.l   BufNewGad,a1
    moveq   #gng_SIZEOF,d0
    jsr     _LVOCopyMem(a6)
    lea.l   BufNewGad,a0
    move.l  VisualInfo,gng_VisualInfo(a0)
    move.l  Font,gng_TextAttr(a0)
    move.w  gng_LeftEdge(a0),d0
    jsr     ComputeX
    add.w   OffX,d0
    move.w  d0,gng_LeftEdge(a0)
    move.w  gng_TopEdge(a0),d0
    jsr     ComputeY
    add.w   OffY,d0
    move.w  d0,gng_TopEdge(a0)
    move.w  gng_Width(a0),d0
    jsr     ComputeX
    move.w  d0,gng_Width(a0)
    move.w  gng_Height(a0),d0
    jsr     ComputeY
    move.w  d0,gng_Height(a0)
    move.l  _GadToolsBase,a6
    lea.l   ABBSAppWindowGTypes,a0
    moveq   #0,d0
    move.l  d3,d1
    asl.l   #1,d1
    add.l   d1,a0
    move.w  (a0),d0
    move.l  a3,a0
    lea.l   BufNewGad,a1
    move.l  a4,a2
    jsr     _LVOCreateGadgetA(a6)
    tst.l   d0
    bne.s    ABBSAppWindowCOK
    movem.w (sp)+,d2-d3
    bra     ABBSAppWindowGError
ABBSAppWindowCOK:
    move.l  d0,a3
    move.l  d3,d0
    asl.l   #2,d0
    lea.l   ABBSAppWindowGadgets,a0
    add.l   d0,a0
    move.l  a3,(a0)
ABBSAppWindowTL:
    tst.l   (a4)
    beq.s   ABBSAppWindowDN
    addq.w  #8,a4
    bra.s   ABBSAppWindowTL
ABBSAppWindowDN:
    addq.w  #4,a4
    addq.w  #1,d3
    cmp.w   #ABBSAppWindow_CNT,d3
    bmi     ABBSAppWindowGL
    movem.w (sp)+,d2-d3
    move.l  ABBSAppWindowGList,ABBSAppWindowWG+4
    move.l  _GadToolsBase,a6
    lea.l   ABBSAppWindowNewMenu0,a0
    lea.l   MTags0,a1
    jsr     _LVOCreateMenusA(a6)
    move.l  d0,ABBSAppWindowMenus
    tst.l   d0
    beq     ABBSAppWindowMError
    move.l  d0,a0
    move.l  VisualInfo,a1
    lea.l   MTags1,a2
    jsr     _LVOLayoutMenusA(a6)
    move.l  Scr,ABBSAppWindowSC+4
    ext.l   d2
    ext.l   d3
    move.l  d2,ABBSAppWindowL+4
    move.l  d3,ABBSAppWindowT+4
    move.l  Scr,a0
    move.w  ABBSAppWindowWidth,d0
    jsr     ComputeX
    add.w   OffX,d0
    move.b  sc_WBorRight(a0),d1
    ext.w   d1
    add.w   d1,d0
    move.l  d0,ABBSAppWindowW+4
    move.w  ABBSAppWindowHeight,d0
    jsr     ComputeY
    add.w   OffY,d0
    move.b  sc_WBorBottom(a0),d1
    ext.w   d1
    add.w   d1,d0
    move.l  d0,ABBSAppWindowH+4
    move.l  _IntuitionBase,a6
    suba.l  a0,a0
    lea.l   ABBSAppWindowWindowTags,a1
    jsr     _LVOOpenWindowTagList(a6)
    move.l  d0,ABBSAppWindowWnd
    tst.l   d0
    beq     ABBSAppWindowWError
    move.l   ABBSAppWindowWnd,a0
    move.l   ABBSAppWindowMenus,a1
    jsr      _LVOSetMenuStrip(a6)
    move.l  _GadToolsBase,a6
    move.l  ABBSAppWindowWnd,a0
    suba.l  a1,a1
    jsr     _LVOGT_RefreshWindow(a6)
    jsr     ABBSAppWindowRender
    moveq   #0,d0
ABBSAppWindowDone:
    movem.l (sp)+,d1-d4/a0-a4/a6
    rts
ABBSAppWindowCError:
    moveq   #1,d0
    bra.s   ABBSAppWindowDone
ABBSAppWindowGError:
    moveq   #2,d0
    bra.s   ABBSAppWindowDone
ABBSAppWindowMError:
    moveq   #3,d0
    bra.s   ABBSAppWindowDone
ABBSAppWindowWError:
    moveq   #4,d0
    bra.s   ABBSAppWindowDone

CloseABBSAppWindowWindow:
    movem.l d0-d1/a0-a2/a6,-(sp)
    move.l   _IntuitionBase,a6
    move.l   ABBSAppWindowMenus,a0
    cmpa.l   #0,a0
    beq      ABBSAppWindowNMenu
    move.l   ABBSAppWindowWnd,a0
    jsr      _LVOClearMenuStrip(a6)
    move.l   _GadToolsBase,a6
    move.l   ABBSAppWindowMenus,a0
    jsr      _LVOFreeMenus(a6)
    move.l   #0,ABBSAppWindowMenus
ABBSAppWindowNMenu:
    move.l  _IntuitionBase,a6
    move.l  ABBSAppWindowWnd,a0
    cmpa.l  #0,a0
    beq     ABBSAppWindowNWnd
    jsr     _LVOCloseWindow(a6)
    move.l  #0,ABBSAppWindowWnd
ABBSAppWindowNWnd:
    move.l  _GadToolsBase,a6
    move.l  ABBSAppWindowGList,a0
    cmpa.l  #0,a0
    beq     ABBSAppWindowNGad
    jsr     _LVOFreeGadgets(a6)
    move.l  #0,ABBSAppWindowGList
ABBSAppWindowNGad:
    movem.l (sp)+,d0-d1/a0-a2/a6
    rts

    end
