/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Andreas Dobloug
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>
#include <pragmas/exec_pragmas.h>
#include <pragmas/intuition_pragmas.h>
#include <pragmas/gadtools_pragmas.h>
#include <pragmas/graphics_pragmas.h>
#include <pragmas/utility_pragmas.h>

#include "ConfigNodegui.h"

static struct Screen         *Scr = NULL;
static UBYTE                 *PubScreenName = "Workbench";
static APTR                   VisualInfo = NULL;
struct Window         *ConfignodeWnd = NULL;
struct Window         *Max_loginWnd = NULL;
struct Window         *Time_betweenWnd = NULL;
static struct Gadget         *ConfignodeGList = NULL;
static struct Gadget         *Max_loginGList = NULL;
static struct Gadget         *Time_betweenGList = NULL;
struct Menu           *ConfignodeMenus = NULL;
struct Gadget         *ConfignodeGadgets[37];
struct Gadget         *Max_loginGadgets[25];
struct Gadget         *Time_betweenGadgets[25];
//extern Class          *initGet( void );
static struct IClass         *getClass = NULL;
static struct _Object        *getImage = NULL;
static UWORD                  ConfignodeLeft = 0;
static UWORD                  ConfignodeTop = 11;
static UWORD                  ConfignodeWidth = 571;
static UWORD                  ConfignodeHeight = 215;
static UWORD                  Max_loginLeft = 100;
static UWORD                  Max_loginTop = 72;
static UWORD                  Max_loginWidth = 438;
static UWORD                  Max_loginHeight = 56;
static UWORD                  Time_betweenLeft = 72;
static UWORD                  Time_betweenTop = 56;
static UWORD                  Time_betweenWidth = 438;
static UWORD                  Time_betweenHeight = 56;
static UBYTE                 *ConfignodeWdt = (UBYTE *)"Confignode 2";
static UBYTE                 *Max_loginWdt = (UBYTE *)"Maximum logintime during this hour";
static UBYTE                 *Time_betweenWdt = (UBYTE *)"Min time between logins during this hour";
static struct TextAttr       *Font, Attr;
static UWORD                  FontX, FontY;
static UWORD                  OffX, OffY;

static UBYTE *Nodetype0Labels[] = {
	(UBYTE *)"Serial node",
	(UBYTE *)"Local node",
	(UBYTE *)"Null modem node",
	NULL };

static UBYTE *screenmode0Labels[] = {
	(UBYTE *)"Default PublicScreen",
	(UBYTE *)"ABBS Screen",
	(UBYTE *)"Public screen",
	NULL };

static UBYTE *node_type0Labels[] = {
	(UBYTE *)"Backdrop",
	(UBYTE *)"Tiny",
	(UBYTE *)"Fullsize",
	NULL };

static struct IntuiText Max_loginIText[] = {
	1, 0, JAM1,103, 8, NULL, (UBYTE *)"1", NULL,
	1, 0, JAM1,140, 8, NULL, (UBYTE *)"2", NULL,
	1, 0, JAM1,178, 8, NULL, (UBYTE *)"3", NULL,
	1, 0, JAM1,215, 8, NULL, (UBYTE *)"4", NULL,
	1, 0, JAM1,252, 8, NULL, (UBYTE *)"5", NULL,
	1, 0, JAM1,290, 8, NULL, (UBYTE *)"6", NULL,
	1, 0, JAM1,327, 8, NULL, (UBYTE *)"7", NULL,
	1, 0, JAM1,366, 8, NULL, (UBYTE *)"8", NULL,
	1, 0, JAM1,403, 8, NULL, (UBYTE *)"9", NULL,
	1, 0, JAM1,20, 19, NULL, (UBYTE *)"0", NULL,
	1, 0, JAM1,20, 31, NULL, (UBYTE *)"1", NULL,
	1, 0, JAM1,19, 44, NULL, (UBYTE *)"2", NULL,
	1, 0, JAM1,64, 8, NULL, (UBYTE *)"0", NULL };

#define Max_login_TNUM 13

static struct IntuiText Time_betweenIText[] = {
	1, 0, JAM1,103, 8, NULL, (UBYTE *)"1", NULL,
	1, 0, JAM1,140, 8, NULL, (UBYTE *)"2", NULL,
	1, 0, JAM1,178, 8, NULL, (UBYTE *)"3", NULL,
	1, 0, JAM1,215, 8, NULL, (UBYTE *)"4", NULL,
	1, 0, JAM1,252, 8, NULL, (UBYTE *)"5", NULL,
	1, 0, JAM1,290, 8, NULL, (UBYTE *)"6", NULL,
	1, 0, JAM1,327, 8, NULL, (UBYTE *)"7", NULL,
	1, 0, JAM1,366, 8, NULL, (UBYTE *)"8", NULL,
	1, 0, JAM1,403, 8, NULL, (UBYTE *)"9", NULL,
	1, 0, JAM1,20, 19, NULL, (UBYTE *)"0", NULL,
	1, 0, JAM1,20, 31, NULL, (UBYTE *)"1", NULL,
	1, 0, JAM1,19, 44, NULL, (UBYTE *)"2", NULL,
	1, 0, JAM1,64, 8, NULL, (UBYTE *)"0", NULL };

#define Time_between_TNUM 13

static struct NewMenu ConfignodeNewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"About", (STRPTR)"A", 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Open Config", (STRPTR)"O", 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Save Config", (STRPTR)"S", 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Quit", (STRPTR)"Q", 0, 0L, NULL,
	NM_END, NULL, NULL, 0, 0L, NULL };

static UWORD ConfignodeGTypes[] = {
	CYCLE_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CYCLE_KIND,
	CYCLE_KIND,
	GENERIC_KIND,
	TEXT_KIND,
	GENERIC_KIND,
	GENERIC_KIND,
	NUMBER_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	STRING_KIND,
	STRING_KIND,
	CHECKBOX_KIND
};

static UWORD Max_loginGTypes[] = {
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	BUTTON_KIND
};

static UWORD Time_betweenGTypes[] = {
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	BUTTON_KIND
};

static struct NewGadget ConfignodeNGad[] = {
	294, 87, 147, 12, NULL, NULL, GD_Nodetype, 0, NULL, NULL,
	14, 198, 259, 11, (UBYTE *)"Set Min Time Between two logins", NULL, GD_Min_between_login, PLACETEXT_IN, NULL, NULL,
	293, 198, 265, 11, (UBYTE *)"Set Max Login Time", NULL, GD_Max_login_time, PLACETEXT_IN, NULL, NULL,
	534, 125, 26, 11, (UBYTE *)"Locked Baud Rate", NULL, GD_Locked_baud_rate, PLACETEXT_LEFT, NULL, NULL,
	370, 125, 26, 11, (UBYTE *)"CTS/RTS", NULL, GD_CTS_RTS, PLACETEXT_LEFT, NULL, NULL,
	534, 139, 26, 11, (UBYTE *)"+++ Hangup", NULL, GD_Hangup_mode, PLACETEXT_LEFT, NULL, NULL,
	250, 176, 26, 11, (UBYTE *)"Open at startup", NULL, GD_Open_at_Startup, PLACETEXT_LEFT, NULL, NULL,
	14, 161, 262, 12, NULL, NULL, GD_screenmode, 0, NULL, NULL,
	14, 176, 97, 12, NULL, NULL, GD_node_type, 0, NULL, NULL,
	538, 175, 20, 14, NULL, NULL, GD_get_font, 0, NULL, NULL,
	331, 176, 133, 12, (UBYTE *)"Font", NULL, GD_font_name, PLACETEXT_LEFT, NULL, NULL,
	256, 87, 20, 14, NULL, NULL, GD_get_hold_path, 0, NULL, NULL,
	256, 101, 20, 14, NULL, NULL, GD_get_tmpdir_path, 0, NULL, NULL,
	510, 176, 25, 12, (UBYTE *)"Size", NULL, GD_font_size, PLACETEXT_LEFT, NULL, NULL,
	108, 88, 147, 12, (UBYTE *)"Hold Path", NULL, GD_Holdpath, PLACETEXT_LEFT, NULL, NULL,
	108, 102, 147, 12, (UBYTE *)"Tmpdir Path", NULL, GD_tmppath, PLACETEXT_LEFT, NULL, NULL,
	114, 125, 52, 12, (UBYTE *)"Window x-pos", NULL, GD_Window_x, PLACETEXT_LEFT, NULL, NULL,
	114, 139, 52, 12, (UBYTE *)"Window y-pos", NULL, GD_Window_y, PLACETEXT_LEFT, NULL, NULL,
	224, 125, 52, 12, (UBYTE *)"Height", NULL, GD_Window_height, PLACETEXT_LEFT, NULL, NULL,
	224, 139, 52, 12, (UBYTE *)"Width", NULL, GD_Window_width, PLACETEXT_LEFT, NULL, NULL,
	149, 6, 119, 12, (UBYTE *)"Modem Init", NULL, GD_Modem_Init, PLACETEXT_LEFT, NULL, NULL,
	149, 18, 119, 12, (UBYTE *)"Modem On Hook", NULL, GD_Modem_on_hook, PLACETEXT_LEFT, NULL, NULL,
	149, 30, 119, 12, (UBYTE *)"Modem Off Hook", NULL, GD_Modem_off_hook, PLACETEXT_LEFT, NULL, NULL,
	149, 42, 119, 12, (UBYTE *)"Modem Answer", NULL, GD_Modem_answer, PLACETEXT_LEFT, NULL, NULL,
	149, 54, 119, 12, (UBYTE *)"Modem Dial", NULL, GD_Modem_dial, PLACETEXT_LEFT, NULL, NULL,
	149, 66, 119, 12, (UBYTE *)"Modem Ring", NULL, GD_Modem_ring, PLACETEXT_LEFT, NULL, NULL,
	454, 6, 104, 12, (UBYTE *)"Modem Connect", NULL, GD_Modem_connect, PLACETEXT_LEFT, NULL, NULL,
	454, 18, 104, 12, (UBYTE *)"Modem No Carrier", NULL, GD_Modem_no_carrier, PLACETEXT_LEFT, NULL, NULL,
	454, 30, 104, 12, (UBYTE *)"Modem AT String", NULL, GD_Modem_at_string, PLACETEXT_LEFT, NULL, NULL,
	454, 42, 104, 12, (UBYTE *)"Modem OK String", NULL, GD_modem_ok_string, PLACETEXT_LEFT, NULL, NULL,
	358, 54, 68, 12, (UBYTE *)"Min Baud", NULL, GD_Minimum_baud, PLACETEXT_LEFT, NULL, NULL,
	427, 54, 36, 12, (UBYTE *)"Connect Wait", NULL, GD_Connect_wait, PLACETEXT_RIGHT, NULL, NULL,
	454, 66, 104, 12, (UBYTE *)"Modem-machine baud", NULL, GD_Modem_machine_baud, PLACETEXT_LEFT, NULL, NULL,
	523, 87, 36, 12, (UBYTE *)"Comm Port", NULL, GD_Comm_port, PLACETEXT_LEFT, NULL, NULL,
	424, 102, 135, 12, (UBYTE *)"Comm port name", NULL, GD_Comm_port_name, PLACETEXT_LEFT, NULL, NULL,
	292, 161, 266, 12, NULL, NULL, GD_publicscren, 0, NULL, NULL,
	370, 140, 26, 11, (UBYTE *)"No Sleep", NULL, GD_NoSleep, PLACETEXT_LEFT, NULL, NULL
};

static struct NewGadget Max_loginNGad[] = {
	46, 38, 37, 12, NULL, NULL, GD_m20, 0, NULL, NULL,
	84, 38, 37, 12, NULL, NULL, GD_m21, 0, NULL, NULL,
	122, 38, 37, 12, NULL, NULL, GD_m22, 0, NULL, NULL,
	160, 38, 37, 12, NULL, NULL, GD_m23, 0, NULL, NULL,
	198, 38, 37, 12, NULL, NULL, GD_m24, 0, NULL, NULL,
	84, 14, 37, 12, NULL, NULL, GD_m1, 0, NULL, NULL,
	122, 14, 37, 12, NULL, NULL, GD_m2, 0, NULL, NULL,
	160, 14, 37, 12, NULL, NULL, GD_m3, 0, NULL, NULL,
	198, 14, 37, 12, NULL, NULL, GD_m4, 0, NULL, NULL,
	236, 14, 37, 12, NULL, NULL, GD_m5, 0, NULL, NULL,
	274, 14, 37, 12, NULL, NULL, GD_m6, 0, NULL, NULL,
	312, 14, 37, 12, NULL, NULL, GD_m7, 0, NULL, NULL,
	350, 14, 37, 12, NULL, NULL, GD_m8, 0, NULL, NULL,
	388, 14, 37, 12, NULL, NULL, GD_m9, 0, NULL, NULL,
	46, 26, 37, 12, NULL, NULL, GD_m10, 0, NULL, NULL,
	84, 26, 37, 12, NULL, NULL, GD_m11, 0, NULL, NULL,
	122, 26, 37, 12, NULL, NULL, GD_m12, 0, NULL, NULL,
	160, 26, 37, 12, NULL, NULL, GD_m13, 0, NULL, NULL,
	198, 26, 37, 12, NULL, NULL, GD_m14, 0, NULL, NULL,
	236, 26, 37, 12, NULL, NULL, GD_m15, 0, NULL, NULL,
	274, 26, 37, 12, NULL, NULL, GD_m16, 0, NULL, NULL,
	312, 26, 37, 12, NULL, NULL, GD_m17, 0, NULL, NULL,
	350, 26, 37, 12, NULL, NULL, GD_m18, 0, NULL, NULL,
	388, 26, 37, 12, NULL, NULL, GD_m19, 0, NULL, NULL,
	349, 40, 76, 11, (UBYTE *)"OK", NULL, GD_Max_time_read_gadgets, PLACETEXT_IN, NULL, NULL
};

static struct NewGadget Time_betweenNGad[] = {
	46, 38, 37, 12, NULL, NULL, GD_b20, 0, NULL, NULL,
	84, 38, 37, 12, NULL, NULL, GD_b21, 0, NULL, NULL,
	122, 38, 37, 12, NULL, NULL, GD_b22, 0, NULL, NULL,
	160, 38, 37, 12, NULL, NULL, GD_b23, 0, NULL, NULL,
	198, 38, 37, 12, NULL, NULL, GD_b24, 0, NULL, NULL,
	84, 14, 37, 12, NULL, NULL, GD_b1, 0, NULL, NULL,
	122, 14, 37, 12, NULL, NULL, GD_b2, 0, NULL, NULL,
	160, 14, 37, 12, NULL, NULL, GD_b3, 0, NULL, NULL,
	198, 14, 37, 12, NULL, NULL, GD_b4, 0, NULL, NULL,
	236, 14, 37, 12, NULL, NULL, GD_b5, 0, NULL, NULL,
	274, 14, 37, 12, NULL, NULL, GD_b6, 0, NULL, NULL,
	312, 14, 37, 12, NULL, NULL, GD_b7, 0, NULL, NULL,
	350, 14, 37, 12, NULL, NULL, GD_b8, 0, NULL, NULL,
	388, 14, 37, 12, NULL, NULL, GD_b9, 0, NULL, NULL,
	46, 26, 37, 12, NULL, NULL, GD_b10, 0, NULL, NULL,
	84, 26, 37, 12, NULL, NULL, GD_b11, 0, NULL, NULL,
	122, 26, 37, 12, NULL, NULL, GD_b12, 0, NULL, NULL,
	160, 26, 37, 12, NULL, NULL, GD_b13, 0, NULL, NULL,
	198, 26, 37, 12, NULL, NULL, GD_b14, 0, NULL, NULL,
	236, 26, 37, 12, NULL, NULL, GD_b15, 0, NULL, NULL,
	274, 26, 37, 12, NULL, NULL, GD_b16, 0, NULL, NULL,
	312, 26, 37, 12, NULL, NULL, GD_b17, 0, NULL, NULL,
	350, 26, 37, 12, NULL, NULL, GD_b18, 0, NULL, NULL,
	388, 26, 37, 12, NULL, NULL, GD_b19, 0, NULL, NULL,
	349, 40, 76, 11, (UBYTE *)"OK", NULL, GD_Min_time_read_gadgets, PLACETEXT_IN, NULL, NULL
};

static ULONG ConfignodeGTags[] = {
	(GTCY_Labels), (ULONG)&Nodetype0Labels[ 0 ], (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTCB_Checked), TRUE, (TAG_DONE),
	(GTCB_Checked), TRUE, (TAG_DONE),
	(TAG_DONE),
	(GTCB_Checked), TRUE, (TAG_DONE),
	(GTCY_Labels), (ULONG)&screenmode0Labels[ 0 ], (GTCY_Active), 1, (TAG_DONE),
	(GTCY_Labels), (ULONG)&node_type0Labels[ 0 ], (GTCY_Active), 2, (TAG_DONE),
	(TAG_DONE),
	(GTTX_Text), (ULONG)"topaz.font     ", (GTTX_Border), TRUE, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTNM_Number), 8, (GTNM_Border), TRUE, (TAG_DONE),
	(GTST_String), (ULONG)"ABBS:hold/node1", (GTST_MaxChars), 30, (TAG_DONE),
	(GTST_String), (ULONG)"T:Node1Tmpdir", (GTST_MaxChars), 30, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 256, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 640, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTST_String), (ULONG)"ATZ", (GTST_MaxChars), 60, (TAG_DONE),
	(GTST_String), (ULONG)"ATH", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"ATH1", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"ATA", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"ATDT", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"RING", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"CONNECT", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"NO CARRIER", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"AT", (GTST_MaxChars), 16, (TAG_DONE),
	(GTST_String), (ULONG)"OK", (GTST_MaxChars), 16, (TAG_DONE),
	(GTIN_Number), 300, (GTIN_MaxChars), 6, (TAG_DONE),
	(GTIN_Number), 30, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 38400, (GTIN_MaxChars), 6, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTST_String), (ULONG)"serial.device", (GTST_MaxChars), 60, (TAG_DONE),
	(GTST_MaxChars), 30, (GA_Disabled), TRUE, (TAG_DONE),
	(GTCB_Checked), TRUE, (TAG_DONE)
};

static ULONG Max_loginGTags[] = {
	(GTIN_Number), 60, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 60, (GTIN_MaxChars), 3, (TAG_DONE),
	(TAG_DONE)
};

static ULONG Time_betweenGTags[] = {
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(TAG_DONE)
};

static UWORD ComputeX( UWORD value )
{
	return(( UWORD )((( FontX * value ) + 4 ) / 8 ));
}

static UWORD ComputeY( UWORD value )
{
	return(( UWORD )((( FontY * value ) + 4 ) / 8 ));
}

static void ComputeFont( UWORD width, UWORD height )
{
	Font = &Attr;
	Font->ta_Name = (STRPTR)Scr->RastPort.Font->tf_Message.mn_Node.ln_Name;
	Font->ta_YSize = FontY = Scr->RastPort.Font->tf_YSize;
	FontX = Scr->RastPort.Font->tf_XSize;

	OffX = Scr->WBorLeft;
	OffY = Scr->RastPort.TxHeight + Scr->WBorTop + 1;

	if ( width && height ) {
		if (( ComputeX( width ) + OffX + Scr->WBorRight ) > Scr->Width )
			goto UseTopaz;
		if (( ComputeY( height ) + OffY + Scr->WBorBottom ) > Scr->Height )
			goto UseTopaz;
	}
	return;

UseTopaz:
	Font->ta_Name = (STRPTR)"topaz.font";
	FontX = FontY = Font->ta_YSize = 8;
}

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( NULL )))
	{
		printf ("HEBBE! 1\n");
		return( 1L );
	}

	ComputeFont( 0, 0 );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
	{
		printf ("HEBBE 2!\n");
		return( 2L );
	}

//	if ( ! ( getClass = initGet()))
//	{
//		printf ("HEBBE 3!\n");
//		return( 3L );
//	}

	if ( ! ( getImage = NewObject( getClass, NULL, GT_VisualInfo, VisualInfo, TAG_DONE )))
	{
		printf ("HEBBE 4!\n");
		return( 4L );
	}

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( getImage   ) {
		DisposeObject( getImage );
		getImage = NULL;
	}

	if ( getClass   ) {
		FreeClass( getClass );
		getClass = NULL;
	}

	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void ConfignodeRender( void )
{
	ComputeFont( ConfignodeWidth, ConfignodeHeight );

	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 5 ),
					OffY + ComputeY( 194 ),
					ComputeX( 278 ),
					ComputeY( 19 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 284 ),
					OffY + ComputeY( 194 ),
					ComputeX( 283 ),
					ComputeY( 19 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 5 ),
					OffY + ComputeY( 120 ),
					ComputeX( 278 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 5 ),
					OffY + ComputeY( 83 ),
					ComputeX( 278 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 5 ),
					OffY + ComputeY( 157 ),
					ComputeX( 562 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 284 ),
					OffY + ComputeY( 120 ),
					ComputeX( 283 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 284 ),
					OffY + ComputeY( 83 ),
					ComputeX( 283 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 5 ),
					OffY + ComputeY( 2 ),
					ComputeX( 278 ),
					ComputeY( 80 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
	DrawBevelBox( ConfignodeWnd->RPort, OffX + ComputeX( 283 ),
					OffY + ComputeY( 2 ),
					ComputeX( 284 ),
					ComputeY( 80 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
}

int OpenConfignodeWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = ConfignodeLeft, wtop = ConfignodeTop, ww, wh;

	ComputeFont( ConfignodeWidth, ConfignodeHeight );

	ww = ComputeX( ConfignodeWidth );
	wh = ComputeY( ConfignodeHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &ConfignodeGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Confignode_CNT; lc++ ) {

		CopyMem((char * )&ConfignodeNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );

		if ( ConfignodeGTypes[ lc ] != GENERIC_KIND ) {
			ng.ng_Width      = ComputeX( ng.ng_Width );
			ng.ng_Height     = ComputeY( ng.ng_Height);
		}

		ConfignodeGadgets[ lc ] = g = CreateGadgetA((ULONG)ConfignodeGTypes[ lc ], g, &ng, ( struct TagItem * )&ConfignodeGTags[ tc ] );

		if ( ConfignodeGTypes[ lc ] == GENERIC_KIND ) {
			g->Flags             |= GFLG_GADGIMAGE | GFLG_GADGHIMAGE;
			g->Activation        |= GACT_RELVERIFY;
			g->GadgetRender       = (APTR)getImage;
			g->SelectRender       = (APTR)getImage;
		}

		while( ConfignodeGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( ConfignodeMenus = CreateMenus( ConfignodeNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( ConfignodeMenus, VisualInfo, TAG_DONE );

	if ( ! ( ConfignodeWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	CYCLEIDCMP|BUTTONIDCMP|CHECKBOXIDCMP|IDCMP_GADGETUP|TEXTIDCMP|NUMBERIDCMP|STRINGIDCMP|INTEGERIDCMP|IDCMP_MENUPICK|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_SUPER_BITMAP|WFLG_ACTIVATE,
				WA_Gadgets,	ConfignodeGList,
				WA_Title,	ConfignodeWdt,
				WA_ScreenTitle,	"Workbench",
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( ConfignodeWnd, ConfignodeMenus );
	GT_RefreshWindow( ConfignodeWnd, NULL );

	ConfignodeRender();

	return( 0L );
}

void CloseConfignodeWindow( void )
{
	if ( ConfignodeMenus      ) {
		ClearMenuStrip( ConfignodeWnd );
		FreeMenus( ConfignodeMenus );
		ConfignodeMenus = NULL;	}

	if ( ConfignodeWnd        ) {
		CloseWindow( ConfignodeWnd );
		ConfignodeWnd = NULL;
	}

	if ( ConfignodeGList      ) {
		FreeGadgets( ConfignodeGList );
		ConfignodeGList = NULL;
	}
}

void Max_loginRender( void )
{
	struct IntuiText	it;
	UWORD			cnt;

	ComputeFont( Max_loginWidth, Max_loginHeight );

	DrawBevelBox( Max_loginWnd->RPort, OffX + ComputeX( 13 ),
					OffY + ComputeY( 13 ),
					ComputeX( 14 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( Max_loginWnd->RPort, OffX + ComputeX( 46 ),
					OffY + ComputeY( 3 ),
					ComputeX( 379 ),
					ComputeY( 9 ),
					GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( Max_loginWnd->RPort, OffX + ComputeX( 3 ),
					OffY + ComputeY( 1 ),
					ComputeX( 433 ),
					ComputeY( 54 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );

	for ( cnt = 0; cnt < Max_login_TNUM; cnt++ ) {
		CopyMem(( char * )&Max_loginIText[ cnt ], ( char * )&it, (long)sizeof( struct IntuiText ));
		it.ITextFont = Font;
		it.LeftEdge  = OffX + ComputeX( it.LeftEdge ) - ( IntuiTextLength( &it ) >> 1 );
		it.TopEdge   = OffY + ComputeY( it.TopEdge ) - ( Font->ta_YSize >> 1 );
		PrintIText( Max_loginWnd->RPort, &it, 0, 0 );
	}
}

int OpenMax_loginWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Max_loginLeft, wtop = Max_loginTop, ww, wh;

	ComputeFont( Max_loginWidth, Max_loginHeight );

	ww = ComputeX( Max_loginWidth );
	wh = ComputeY( Max_loginHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Max_loginGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Max_login_CNT; lc++ ) {

		CopyMem((char * )&Max_loginNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Max_loginGadgets[ lc ] = g = CreateGadgetA((ULONG)Max_loginGTypes[ lc ], g, &ng, ( struct TagItem * )&Max_loginGTags[ tc ] );

		while( Max_loginGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Max_loginWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	INTEGERIDCMP|BUTTONIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	Max_loginGList,
				WA_Title,	Max_loginWdt,
				WA_ScreenTitle,	"Workbench",
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Max_loginWnd, NULL );

	Max_loginRender();

	return( 0L );
}

void CloseMax_loginWindow( void )
{
	if ( Max_loginWnd        ) {
		CloseWindow( Max_loginWnd );
		Max_loginWnd = NULL;
	}

	if ( Max_loginGList      ) {
		FreeGadgets( Max_loginGList );
		Max_loginGList = NULL;
	}
}

void Time_betweenRender( void )
{
	struct IntuiText	it;
	UWORD			cnt;

	ComputeFont( Time_betweenWidth, Time_betweenHeight );

	DrawBevelBox( Time_betweenWnd->RPort, OffX + ComputeX( 13 ),
					OffY + ComputeY( 13 ),
					ComputeX( 14 ),
					ComputeY( 36 ),
					GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( Time_betweenWnd->RPort, OffX + ComputeX( 46 ),
					OffY + ComputeY( 3 ),
					ComputeX( 379 ),
					ComputeY( 9 ),
					GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( Time_betweenWnd->RPort, OffX + ComputeX( 3 ),
					OffY + ComputeY( 1 ),
					ComputeX( 433 ),
					ComputeY( 54 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );

	for ( cnt = 0; cnt < Time_between_TNUM; cnt++ ) {
		CopyMem(( char * )&Time_betweenIText[ cnt ], ( char * )&it, (long)sizeof( struct IntuiText ));
		it.ITextFont = Font;
		it.LeftEdge  = OffX + ComputeX( it.LeftEdge ) - ( IntuiTextLength( &it ) >> 1 );
		it.TopEdge   = OffY + ComputeY( it.TopEdge ) - ( Font->ta_YSize >> 1 );
		PrintIText( Time_betweenWnd->RPort, &it, 0, 0 );
	}
}

int OpenTime_betweenWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = Time_betweenLeft, wtop = Time_betweenTop, ww, wh;

	ComputeFont( Time_betweenWidth, Time_betweenHeight );

	ww = ComputeX( Time_betweenWidth );
	wh = ComputeY( Time_betweenHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &Time_betweenGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Time_between_CNT; lc++ ) {

		CopyMem((char * )&Time_betweenNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		Time_betweenGadgets[ lc ] = g = CreateGadgetA((ULONG)Time_betweenGTypes[ lc ], g, &ng, ( struct TagItem * )&Time_betweenGTags[ tc ] );

		while( Time_betweenGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( Time_betweenWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	INTEGERIDCMP|BUTTONIDCMP|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	Time_betweenGList,
				WA_Title,	Time_betweenWdt,
				WA_ScreenTitle,	"Workbench",
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( Time_betweenWnd, NULL );

	Time_betweenRender();

	return( 0L );
}

void CloseTime_betweenWindow( void )
{
	if ( Time_betweenWnd        ) {
		CloseWindow( Time_betweenWnd );
		Time_betweenWnd = NULL;
	}

	if ( Time_betweenGList      ) {
		FreeGadgets( Time_betweenGList );
		Time_betweenGList = NULL;
	}
}

