/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Geir Inge Høsteng
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Users_ListView                      0
#define GD_username                            1
#define GD_address                             2
#define GD_citystate                           3
#define GD_passwd                              4
#define GD_homephone                           5
#define GD_workphone                           6
#define GD_timelimit                           7
#define GD_filelimit                           8
#define GD_pagelength                          9
#define GD_protocol                            10
#define GD_charset                             11
#define GD_scratchformat                       12
#define GD_xpertlevel                          13
#define GD_Killed                              14
#define GD_usefse                              15
#define GD_ansimenus                           16
#define GD_colormsg                            17
#define GD_g_r                                 18
#define GD_reviewown                           19
#define GD_ansi                                20
#define GD_clearscreen                         21
#define GD_raw                                 22
#define GD_filter                              23
#define GD_sendbulletins                       24
#define GD_lastontext                          25
#define GD_resymemsgnr                         26
#define GD_timeused                            27
#define GD_Gadget280                           28
#define GD_grabformat                          29
#define GD_byteratio                           30
#define GD_fileratio                           31
#define GD_uploaded                            32
#define GD_downloaded                          33
#define GD_kbupload                            34
#define GD_kbdownload                          35
#define GD_timeson                             36
#define GD_ftimeused                           37
#define GD_msgread                             38
#define GD_msgdumped                           39
#define GD_totaltime                           40
#define GD_conference_listview                 41
#define GD_msgleft                             42
#define GD_saveuser                            43

#define GDX_Users_ListView                     0
#define GDX_username                           1
#define GDX_address                            2
#define GDX_citystate                          3
#define GDX_passwd                             4
#define GDX_homephone                          5
#define GDX_workphone                          6
#define GDX_timelimit                          7
#define GDX_filelimit                          8
#define GDX_pagelength                         9
#define GDX_protocol                           10
#define GDX_charset                            11
#define GDX_scratchformat                      12
#define GDX_xpertlevel                         13
#define GDX_Killed                             14
#define GDX_usefse                             15
#define GDX_ansimenus                          16
#define GDX_colormsg                           17
#define GDX_g_r                                18
#define GDX_reviewown                          19
#define GDX_ansi                               20
#define GDX_clearscreen                        21
#define GDX_raw                                22
#define GDX_filter                             23
#define GDX_sendbulletins                      24
#define GDX_lastontext                         25
#define GDX_resymemsgnr                        26
#define GDX_timeused                           27
#define GDX_Gadget280                          28
#define GDX_grabformat                         29
#define GDX_byteratio                          30
#define GDX_fileratio                          31
#define GDX_uploaded                           32
#define GDX_downloaded                         33
#define GDX_kbupload                           34
#define GDX_kbdownload                         35
#define GDX_timeson                            36
#define GDX_ftimeused                          37
#define GDX_msgread                            38
#define GDX_msgdumped                          39
#define GDX_totaltime                          40
#define GDX_conference_listview                41
#define GDX_msgleft                            42
#define GDX_saveuser                           43

#define ABBSUserEditor_CNT 44

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct GfxBase       *GfxBase;
extern struct MinList        Users_ListView0List;
extern struct MinList        conference_listview0List;


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void ABBSUserEditorRender( void );
extern int OpenABBSUserEditorWindow( void );
extern void CloseABBSUserEditorWindow( void );
