/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Geir Inge Høsteng
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>
#include <clib/diskfont_protos.h>

#include <pragmas/exec_pragmas.h>
#include <pragmas/intuition_pragmas.h>
#include <pragmas/gadtools_pragmas.h>
#include <pragmas/graphics_pragmas.h>
#include <pragmas/utility_pragmas.h>

#include "Usereditorgui.h"

#include <proto/diskfont.h>

static struct Screen         *Scr = NULL;
static UBYTE                 *PubScreenName = NULL;
static APTR                   VisualInfo = NULL;
struct Window         *ABBSUserEditorWnd = NULL;
static struct Gadget         *ABBSUserEditorGList = NULL;
struct Menu           *ABBSUserEditorMenus = NULL;
struct Gadget         *ABBSUserEditorGadgets[44];
static UWORD                  ABBSUserEditorLeft = 0;
static UWORD                  ABBSUserEditorTop = 13;
static UWORD                  ABBSUserEditorWidth = 558;
static UWORD                  ABBSUserEditorHeight = 288;
static UBYTE                 *ABBSUserEditorWdt = (UBYTE *)"ABBS UserEditor";
static struct TextAttr       *Font, Attr;
static UWORD                  FontX, FontY;
static UWORD                  OffX, OffY;
static struct TextFont       *ABBSUserEditorFont = NULL;

static UBYTE *protocol0Labels[] = {
	(UBYTE *)"(none)",
	(UBYTE *)"Zmodem",
	(UBYTE *)"Xmodem",
	(UBYTE *)"Xmodem-CRC",
	(UBYTE *)"Ymodem",
	(UBYTE *)"Ymodem-Batch",
	(UBYTE *)"Ymodem-G",
	NULL };

static UBYTE *charset0Labels[] = {
	(UBYTE *)"ISO",
	(UBYTE *)"IBM",
	(UBYTE *)"IBN",
	(UBYTE *)"US7",
	(UBYTE *)"UK7",
	(UBYTE *)"GE7",
	(UBYTE *)"FR7",
	(UBYTE *)"SF7",
	(UBYTE *)"NO7",
	(UBYTE *)"DE7",
	(UBYTE *)"SP7",
	(UBYTE *)"IT7",
	NULL };

static UBYTE *scratchformat0Labels[] = {
	(UBYTE *)"Text",
	(UBYTE *)"Arc",
	(UBYTE *)"Lzh",
	(UBYTE *)"Zip",
	(UBYTE *)"Lharc",
	(UBYTE *)"Arj",
	(UBYTE *)"Zoo",
	NULL };

static UBYTE *xpertlevel0Labels[] = {
	(UBYTE *)"Novice",
	(UBYTE *)"Junior",
	(UBYTE *)"Expert",
	(UBYTE *)"SuperExpert",
	NULL };

static UBYTE *grabformat0Labels[] = {
	(UBYTE *)"MBBS",
	(UBYTE *)"QWK",
	NULL };

static struct Node Users_ListView0Nodes[] = {
	( struct Node * )&Users_ListView0List.mlh_Tail, ( struct Node * )&Users_ListView0List.mlh_Head, 0, 0, "." };

struct MinList Users_ListView0List = {
	( struct MinNode * )&Users_ListView0Nodes[0], ( struct MinNode * )NULL, ( struct MinNode * )&Users_ListView0Nodes[0] };

static struct Node conference_listview0Nodes[] = {
	( struct Node * )&conference_listview0List.mlh_Tail, ( struct Node * )&conference_listview0List.mlh_Head, 0, 0, "." };

struct MinList conference_listview0List = {
	( struct MinNode * )&conference_listview0Nodes[0], ( struct MinNode * )NULL, ( struct MinNode * )&conference_listview0Nodes[0] };

static struct NewMenu ABBSUserEditorNewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"About", (STRPTR)"A", 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Save user", (STRPTR)"S", 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Quit", (STRPTR)"Q", 0, 0L, NULL,
	NM_END, NULL, NULL, 0, 0L, NULL };

static UWORD ABBSUserEditorGTypes[] = {
	LISTVIEW_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	CYCLE_KIND,
	CYCLE_KIND,
	CYCLE_KIND,
	CYCLE_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	TEXT_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	MX_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	LISTVIEW_KIND,
	INTEGER_KIND,
	BUTTON_KIND
};

static struct NewGadget ABBSUserEditorNGad[] = {
	273, 15, 265, 145, (UBYTE *)"Users", NULL, GD_Users_ListView, PLACETEXT_ABOVE|NG_HIGHLABEL, NULL, NULL,
	9, 5, 252, 13, NULL, NULL, GD_username, 0, NULL, NULL,
	9, 21, 252, 13, NULL, NULL, GD_address, 0, NULL, NULL,
	9, 37, 252, 13, NULL, NULL, GD_citystate, 0, NULL, NULL,
	155, 53, 77, 13, NULL, NULL, GD_passwd, 0, NULL, NULL,
	9, 53, 140, 13, NULL, NULL, GD_homephone, 0, NULL, NULL,
	9, 69, 140, 13, NULL, NULL, GD_workphone, 0, NULL, NULL,
	9, 85, 36, 13, NULL, NULL, GD_timelimit, 0, NULL, NULL,
	51, 85, 36, 13, NULL, NULL, GD_filelimit, 0, NULL, NULL,
	92, 85, 36, 13, NULL, NULL, GD_pagelength, 0, NULL, NULL,
	136, 85, 122, 13, NULL, NULL, GD_protocol, 0, NULL, NULL,
	155, 69, 71, 13, NULL, NULL, GD_charset, 0, NULL, NULL,
	9, 101, 71, 13, NULL, NULL, GD_scratchformat, 0, NULL, NULL,
	86, 100, 118, 13, NULL, NULL, GD_xpertlevel, 0, NULL, NULL,
	9, 117, 26, 11, (UBYTE *)"Killed", NULL, GD_Killed, PLACETEXT_RIGHT, NULL, NULL,
	9, 129, 26, 11, (UBYTE *)"Use FSE", NULL, GD_usefse, PLACETEXT_RIGHT, NULL, NULL,
	9, 141, 26, 11, (UBYTE *)"ANSI menus", NULL, GD_ansimenus, PLACETEXT_RIGHT, NULL, NULL,
	9, 153, 26, 11, (UBYTE *)"Color msgs", NULL, GD_colormsg, PLACETEXT_RIGHT, NULL, NULL,
	9, 165, 26, 11, (UBYTE *)"G&R", NULL, GD_g_r, PLACETEXT_RIGHT, NULL, NULL,
	9, 177, 26, 11, (UBYTE *)"Review own", NULL, GD_reviewown, PLACETEXT_RIGHT, NULL, NULL,
	9, 189, 26, 11, (UBYTE *)"ANSI", NULL, GD_ansi, PLACETEXT_RIGHT, NULL, NULL,
	9, 201, 26, 11, (UBYTE *)"Clear Scr.", NULL, GD_clearscreen, PLACETEXT_RIGHT, NULL, NULL,
	9, 213, 26, 11, (UBYTE *)"Use Raw", NULL, GD_raw, PLACETEXT_RIGHT, NULL, NULL,
	9, 224, 26, 11, (UBYTE *)"Filter", NULL, GD_filter, PLACETEXT_RIGHT, NULL, NULL,
	9, 235, 26, 11, (UBYTE *)"Send bulletins", NULL, GD_sendbulletins, PLACETEXT_RIGHT, NULL, NULL,
	7, 268, 255, 13, NULL, NULL, GD_lastontext, 0, NULL, NULL,
	134, 117, 68, 13, NULL, NULL, GD_resymemsgnr, 0, NULL, NULL,
	175, 148, 36, 13, NULL, NULL, GD_timeused, 0, NULL, NULL,
	135, 133, 36, 13, NULL, NULL, GD_Gadget280, 0, NULL, NULL,
	12, 248, 17, 9, NULL, NULL, GD_grabformat, PLACETEXT_RIGHT, NULL, NULL,
	134, 148, 36, 13, NULL, NULL, GD_byteratio, 0, NULL, NULL,
	134, 164, 36, 13, NULL, NULL, GD_fileratio, 0, NULL, NULL,
	134, 179, 36, 13, NULL, NULL, GD_uploaded, 0, NULL, NULL,
	134, 194, 36, 13, NULL, NULL, GD_downloaded, 0, NULL, NULL,
	134, 209, 36, 13, NULL, NULL, GD_kbupload, 0, NULL, NULL,
	134, 223, 36, 13, NULL, NULL, GD_kbdownload, 0, NULL, NULL,
	175, 133, 52, 13, NULL, NULL, GD_timeson, 0, NULL, NULL,
	175, 164, 36, 13, NULL, NULL, GD_ftimeused, 0, NULL, NULL,
	175, 179, 52, 13, NULL, NULL, GD_msgread, 0, NULL, NULL,
	175, 194, 52, 13, NULL, NULL, GD_msgdumped, 0, NULL, NULL,
	175, 223, 52, 13, NULL, NULL, GD_totaltime, 0, NULL, NULL,
	275, 168, 265, 121, (UBYTE *)"Conferences", NULL, GD_conference_listview, PLACETEXT_ABOVE|NG_HIGHLABEL, NULL, NULL,
	175, 209, 52, 13, NULL, NULL, GD_msgleft, 0, NULL, NULL,
	137, 247, 103, 14, (UBYTE *)"Save user", NULL, GD_saveuser, PLACETEXT_IN, NULL, NULL
};

static ULONG ABBSUserEditorGTags[] = {
	(TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 8, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTCY_Labels), (ULONG)&protocol0Labels[ 0 ], (TAG_DONE),
	(GTCY_Labels), (ULONG)&charset0Labels[ 0 ], (TAG_DONE),
	(GTCY_Labels), (ULONG)&scratchformat0Labels[ 0 ], (TAG_DONE),
	(GTCY_Labels), (ULONG)&xpertlevel0Labels[ 0 ], (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTTX_Border), TRUE, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 8, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTMX_Labels), (ULONG)&grabformat0Labels[ 0 ], (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (TAG_DONE),
	(TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 5, (TAG_DONE),
	(TAG_DONE)
};

static UWORD ComputeX( UWORD value )
{
	return(( UWORD )((( FontX * value ) + 4 ) / 8 ));
}

static UWORD ComputeY( UWORD value )
{
	return(( UWORD )((( FontY * value ) + 4 ) / 8 ));
}

static void ComputeFont( UWORD width, UWORD height )
{
	Forbid();
	Font = &Attr;
	Font->ta_Name = (STRPTR)GfxBase->DefaultFont->tf_Message.mn_Node.ln_Name;
	Font->ta_YSize = FontY = GfxBase->DefaultFont->tf_YSize;
	FontX = GfxBase->DefaultFont->tf_XSize;
	Permit();

	OffX = Scr->WBorLeft;
	OffY = Scr->RastPort.TxHeight + Scr->WBorTop + 1;

	if ( width && height ) {
		if (( ComputeX( width ) + OffX + Scr->WBorRight ) > Scr->Width )
			goto UseTopaz;
		if (( ComputeY( height ) + OffY + Scr->WBorBottom ) > Scr->Height )
			goto UseTopaz;
	}
	return;

UseTopaz:
	Font->ta_Name = (STRPTR)"topaz.font";
	FontX = FontY = Font->ta_YSize = 8;
}

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	ComputeFont( 0, 0 );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void ABBSUserEditorRender( void )
{
	ComputeFont( ABBSUserEditorWidth, ABBSUserEditorHeight );

	DrawBevelBox( ABBSUserEditorWnd->RPort, OffX + ComputeX( 3 ),
					OffY + ComputeY( 2 ),
					ComputeX( 264 ),
					ComputeY( 284 ),
					GT_VisualInfo, VisualInfo, TAG_DONE );
}

int OpenABBSUserEditorWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = ABBSUserEditorLeft, wtop = ABBSUserEditorTop, ww, wh;

	ComputeFont( ABBSUserEditorWidth, ABBSUserEditorHeight );

	ww = ComputeX( ABBSUserEditorWidth );
	wh = ComputeY( ABBSUserEditorHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( ABBSUserEditorFont = OpenDiskFont( Font )))
		return( 5L );

	if ( ! ( g = CreateContext( &ABBSUserEditorGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < ABBSUserEditor_CNT; lc++ ) {

		CopyMem((char * )&ABBSUserEditorNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		ABBSUserEditorGadgets[ lc ] = g = CreateGadgetA((ULONG)ABBSUserEditorGTypes[ lc ], g, &ng, ( struct TagItem * )&ABBSUserEditorGTags[ tc ] );

		while( ABBSUserEditorGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( ABBSUserEditorMenus = CreateMenus( ABBSUserEditorNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( ABBSUserEditorMenus, VisualInfo, TAG_DONE );

	if ( ! ( ABBSUserEditorWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	LISTVIEWIDCMP|STRINGIDCMP|INTEGERIDCMP|CYCLEIDCMP|CHECKBOXIDCMP|TEXTIDCMP|MXIDCMP|BUTTONIDCMP|IDCMP_MENUPICK|IDCMP_CLOSEWINDOW|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_SIZEGADGET|WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	ABBSUserEditorGList,
				WA_Title,	ABBSUserEditorWdt,
				WA_ScreenTitle,	"WorkBench Screen",
				WA_PubScreen,	Scr,
				WA_MinWidth,	67,
				WA_MinHeight,	21,
				WA_MaxWidth,	912,
				WA_MaxHeight,	600,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( ABBSUserEditorWnd, ABBSUserEditorMenus );
	GT_RefreshWindow( ABBSUserEditorWnd, NULL );

	ABBSUserEditorRender();

	return( 0L );
}

void CloseABBSUserEditorWindow( void )
{
	if ( ABBSUserEditorMenus      ) {
		ClearMenuStrip( ABBSUserEditorWnd );
		FreeMenus( ABBSUserEditorMenus );
		ABBSUserEditorMenus = NULL;	}

	if ( ABBSUserEditorWnd        ) {
		CloseWindow( ABBSUserEditorWnd );
		ABBSUserEditorWnd = NULL;
	}

	if ( ABBSUserEditorGList      ) {
		FreeGadgets( ABBSUserEditorGList );
		ABBSUserEditorGList = NULL;
	}

	if ( ABBSUserEditorFont ) {
		CloseFont( ABBSUserEditorFont );
		ABBSUserEditorFont = NULL;
	}
}

