/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Geir Inge Høsteng
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_ListGadget                          0
#define GD_Cancelgadget                        1
#define GD_OKGadget                            2

#define GDX_ListGadget                         0
#define GDX_Cancelgadget                       1
#define GDX_OKGadget                           2

#define Select_CNT 3

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct GfxBase       *GfxBase;
extern struct MinList        ListGadget0List;


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenSelectWindow( void );
extern void CloseSelectWindow( void );
