	XREF	savemsgheader
	XREF	loadmsgheader
	XREF	loadmsgtext
	XREF	loadmsg
	XREF	savemsg
	XREF	sendintermsg
	XREF	doallusers
	XREF	handlemsg
	XREF	handlemsgspesport
	XREF	sendmsgspesport
	XREF	getnamenrmatch
	XREF	getusernumber
	XREF	loadusernrnr
	XREF	saveusernrnr
	XREF	loadusernr
	XREF	saveusernr
	XREF	loaduser
	XREF	saveuser
	XREF	saveconfig
	XREF	lockoutallothernodes
	XREF	unlockoutallothernodes
	XREF	askopenscreen
	XREF	askclosescreen
