	XREF	firstzoom
	XREF	NewWindowStructure1
	XREF	windowtags
	XREF	warningtimearr
	XREF	daytext
	XREF	monthtext
	XREF	xprbaudates
	XREF	convertISOtoxxx
	XREF	convertxxxtoISO
	XREF	charsettext
	XREF	transwhat7bitchar
	XREF	fraISO7tilISO8
	XREF	fraISO8tilISO7
