/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_NAME                                0
#define GD_PASSWORD                            1
#define GD_ADDRESS                             2
#define GD_CITY                                3
#define GD_HOMEPHONE                           4
#define GD_WORKPHONE                           5
#define GD_BOARDNAME                           6
#define GD_TIMELIMIT                           7
#define GD_FILETIMELIMIT                       8
#define GD_MAXLINESINMSGS                      9
#define GD_SLEEPTIME                           10
#define GD_KBRATIO                             11
#define GD_FILERATIO                           12
#define GD_MINULSPACE                          13
#define GD_BYTE_ON                             14
#define GD_FILE_ON                             15
#define GD_DOS_PASSWORD                        16

#define GDX_NAME                               0
#define GDX_PASSWORD                           1
#define GDX_ADDRESS                            2
#define GDX_CITY                               3
#define GDX_HOMEPHONE                          4
#define GDX_WORKPHONE                          5
#define GDX_BOARDNAME                          6
#define GDX_TIMELIMIT                          7
#define GDX_FILETIMELIMIT                      8
#define GDX_MAXLINESINMSGS                     9
#define GDX_SLEEPTIME                          10
#define GDX_KBRATIO                            11
#define GDX_FILERATIO                          12
#define GDX_MINULSPACE                         13
#define GDX_BYTE_ON                            14
#define GDX_FILE_ON                            15
#define GDX_DOS_PASSWORD                       16

#define ConfigBBS_CNT 17

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ConfigBBSWnd;
extern struct Gadget        *ConfigBBSGList;
extern struct Menu          *ConfigBBSMenus;
extern struct Gadget        *ConfigBBSGadgets[17];
extern UWORD                 ConfigBBSLeft;
extern UWORD                 ConfigBBSTop;
extern UWORD                 ConfigBBSWidth;
extern UWORD                 ConfigBBSHeight;
extern UBYTE                *ConfigBBSWdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      ConfigBBSIText[];
extern struct NewMenu        ConfigBBSNewMenu[];
extern UWORD                 ConfigBBSGTypes[];
extern struct NewGadget      ConfigBBSNGad[];
extern ULONG                 ConfigBBSGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void ConfigBBSRender( void );
extern int OpenConfigBBSWindow( void );
extern void CloseConfigBBSWindow( void );
