/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include "ConfigBBS_GUI.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *ConfigBBSWnd = NULL;
struct Gadget         *ConfigBBSGList = NULL;
struct Menu           *ConfigBBSMenus = NULL;
struct Gadget         *ConfigBBSGadgets[17];
UWORD                  ConfigBBSLeft = 0;
UWORD                  ConfigBBSTop = 0;
UWORD                  ConfigBBSWidth = 656;
UWORD                  ConfigBBSHeight = 233;
UBYTE                 *ConfigBBSWdt = (UBYTE *)"ConfigBBS II";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

struct IntuiText ConfigBBSIText[] = {
	2, 0, JAM1,168, 9, &topaz8, (UBYTE *)"SYSOP INFO", &ConfigBBSIText[1],
	1, 0, JAM1,26, 25, &topaz8, (UBYTE *)"Name", &ConfigBBSIText[2],
	1, 0, JAM1,26, 55, &topaz8, (UBYTE *)"Address", &ConfigBBSIText[3],
	1, 0, JAM1,26, 85, &topaz8, (UBYTE *)"Postal code", &ConfigBBSIText[4],
	1, 0, JAM1,26, 115, &topaz8, (UBYTE *)"Home phone", &ConfigBBSIText[5],
	1, 0, JAM1,192, 115, &topaz8, (UBYTE *)"Work phone", &ConfigBBSIText[6],
	1, 0, JAM1,26, 165, &topaz8, (UBYTE *)"BBS name (grab name)", &ConfigBBSIText[7],
	1, 0, JAM1,299, 23, &topaz8, (UBYTE *)"Local pw", &ConfigBBSIText[8],
	1, 0, JAM1,299, 54, &topaz8, (UBYTE *)"DOS pw", NULL };

struct NewMenu ConfigBBSNewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Load config", (STRPTR)"L", 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Save config", (STRPTR)"S", 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"Quit", (STRPTR)"Q", 0, 0L, NULL,
	NM_TITLE, (STRPTR)"Features", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Interlaced", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_ITEM, (STRPTR)"8 colours", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_ITEM, (STRPTR)"Allow TmpSysop", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_ITEM, (STRPTR)"Use ASL", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)"New user charset", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"ISO", NULL, CHECKIT, 0L, NULL,
	NM_SUB, (STRPTR)"IBM", NULL, CHECKIT, 0L, NULL,
	NM_SUB, (STRPTR)"IBN", NULL, CHECKIT, 0L, NULL,
	NM_TITLE, (STRPTR)"New users may", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Upload", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_ITEM, (STRPTR)"Download", NULL, CHECKIT|MENUTOGGLE, 0L, NULL,
	NM_END, NULL, NULL, 0, 0L, NULL };

UWORD ConfigBBSGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	STRING_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	INTEGER_KIND,
	CHECKBOX_KIND,
	CHECKBOX_KIND,
	STRING_KIND
};

struct NewGadget ConfigBBSNGad[] = {
	27, 34, 261, 15, NULL, NULL, GD_NAME, 0, NULL, NULL,
	299, 34, 85, 15, NULL, NULL, GD_PASSWORD, 0, NULL, NULL,
	27, 64, 261, 15, NULL, NULL, GD_ADDRESS, 0, NULL, NULL,
	27, 94, 261, 15, NULL, NULL, GD_CITY, 0, NULL, NULL,
	26, 124, 148, 15, NULL, NULL, GD_HOMEPHONE, 0, NULL, NULL,
	192, 124, 148, 15, NULL, NULL, GD_WORKPHONE, 0, NULL, NULL,
	25, 174, 261, 15, NULL, NULL, GD_BOARDNAME, 0, NULL, NULL,
	581, 24, 53, 14, (UBYTE *)"Time limit:", NULL, GD_TIMELIMIT, PLACETEXT_LEFT, NULL, NULL,
	581, 39, 53, 14, (UBYTE *)"File time limit:", NULL, GD_FILETIMELIMIT, PLACETEXT_LEFT, NULL, NULL,
	581, 54, 53, 14, (UBYTE *)"Max lines in msgs:", NULL, GD_MAXLINESINMSGS, PLACETEXT_LEFT, NULL, NULL,
	581, 69, 53, 14, (UBYTE *)"Sleep time:", NULL, GD_SLEEPTIME, PLACETEXT_LEFT, NULL, NULL,
	581, 84, 53, 14, (UBYTE *)"KB ratio:", NULL, GD_KBRATIO, PLACETEXT_LEFT, NULL, NULL,
	581, 99, 53, 14, (UBYTE *)"File ratio:", NULL, GD_FILERATIO, PLACETEXT_LEFT, NULL, NULL,
	581, 114, 53, 14, (UBYTE *)"Min upload space:", NULL, GD_MINULSPACE, PLACETEXT_LEFT, NULL, NULL,
	454, 85, 26, 11, NULL, NULL, GD_BYTE_ON, 0, NULL, NULL,
	454, 100, 26, 11, NULL, NULL, GD_FILE_ON, 0, NULL, NULL,
	299, 64, 85, 15, NULL, NULL, GD_DOS_PASSWORD, 0, NULL, NULL
};

ULONG ConfigBBSGTags[] = {
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 8, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 16, (TAG_DONE),
	(GTST_MaxChars), 30, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 2, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 4, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(GTIN_Number), 0, (GTIN_MaxChars), 3, (TAG_DONE),
	(TAG_DONE),
	(TAG_DONE),
	(GTST_MaxChars), 8, (TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

void ConfigBBSRender( void )
{
	UWORD		offx, offy;

	offx = ConfigBBSWnd->BorderLeft;
	offy = ConfigBBSWnd->BorderTop;


	DrawBevelBox( ConfigBBSWnd->RPort, offx + 414, offy + 19, 234, 115, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	DrawBevelBox( ConfigBBSWnd->RPort, offx + 12, offy + 19, 386, 129, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
	PrintIText( ConfigBBSWnd->RPort, ConfigBBSIText, offx, offy );
}

int OpenConfigBBSWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &ConfigBBSGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < ConfigBBS_CNT; lc++ ) {

		CopyMem((char * )&ConfigBBSNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		ConfigBBSGadgets[ lc ] = g = CreateGadgetA((ULONG)ConfigBBSGTypes[ lc ], g, &ng, ( struct TagItem * )&ConfigBBSGTags[ tc ] );

		while( ConfigBBSGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( ConfigBBSMenus = CreateMenus( ConfigBBSNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( ConfigBBSMenus, VisualInfo, GTMN_TextAttr, &topaz8, TAG_DONE );

	if ( ! ( ConfigBBSWnd = OpenWindowTags( NULL,
				WA_Left,	ConfigBBSLeft,
				WA_Top,		ConfigBBSTop,
				WA_Width,	ConfigBBSWidth,
				WA_Height,	ConfigBBSHeight + offy,
				WA_IDCMP,	STRINGIDCMP|INTEGERIDCMP|CHECKBOXIDCMP|IDCMP_MENUPICK|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	ConfigBBSGList,
				WA_Title,	ConfigBBSWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( ConfigBBSWnd, ConfigBBSMenus );
	GT_RefreshWindow( ConfigBBSWnd, NULL );

	ConfigBBSRender();

	return( 0L );
}

void CloseConfigBBSWindow( void )
{
	if ( ConfigBBSMenus      ) {
		ClearMenuStrip( ConfigBBSWnd );
		FreeMenus( ConfigBBSMenus );
		ConfigBBSMenus = NULL;	}

	if ( ConfigBBSWnd        ) {
		CloseWindow( ConfigBBSWnd );
		ConfigBBSWnd = NULL;
	}

	if ( ConfigBBSGList      ) {
		FreeGadgets( ConfigBBSGList );
		ConfigBBSGList = NULL;
	}
}

