/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include "GUI.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = NULL;
APTR                   VisualInfo = NULL;
struct Window         *FileEditorWnd = NULL;
struct Window         *EditWnd = NULL;
struct Gadget         *FileEditorGList = NULL;
struct Gadget         *EditGList = NULL;
struct Menu           *FileEditorMenus = NULL;
struct Menu           *EditMenus = NULL;
struct Gadget         *FileEditorGadgets[2];
struct Gadget         *EditGadgets[5];
UWORD                  FileEditorLeft = 0;
UWORD                  FileEditorTop = 0;
UWORD                  FileEditorWidth = 647;
UWORD                  FileEditorHeight = 221;
UWORD                  EditLeft = 0;
UWORD                  EditTop = 0;
UWORD                  EditWidth = 525;
UWORD                  EditHeight = 160;
UBYTE                 *FileEditorWdt = (UBYTE *)"FileEditor";

struct TextAttr topaz8 = {
	( STRPTR )"topaz.font", 8, 0x00, 0x01 };

char m_Project[20];
char m_About[20];
char m_Quit[20];
char m_Directories[20];
char m_New[20];
char m_Change_name[20];
char m_Change_path[20];
char m_Delete[20];
char m_Update[20];
char m_File[20];
char m_Auto_install[20];
char m_Edit[20];
char m_Update_file_sizes[30];
char m_Count_files[20];
char m_Update_preview_files[30];
char m_Comments[20];
char m_Auto_search[20];
char m_From_file_list[20];
char m_Checking[20];
char m_Test_archives[20];
char m_Virus_check[20];
char m_Delete_move_not_installed_files[40];

struct NewMenu FileEditorNewMenu[] = {
	NM_TITLE, (STRPTR)m_Project, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)m_About, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Quit, (STRPTR)"Q", 0, 0L, NULL,

	NM_TITLE, (STRPTR)m_Directories, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)m_New, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Change_name, NULL, NM_ITEMDISABLED, 0L, NULL,
	NM_ITEM, (STRPTR)m_Change_path, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Delete, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Update, NULL, 0, 0L, NULL,

	NM_TITLE, (STRPTR)m_File, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)m_Auto_install, (STRPTR)"A", 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Edit, (STRPTR)"E", 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Delete, (STRPTR)"D", 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Update_file_sizes, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Count_files, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Update_preview_files, NULL, NM_ITEMDISABLED, 0L, NULL,

	NM_TITLE, (STRPTR)m_Comments, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)m_Auto_search, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_From_file_list, NULL, 0, 0L, NULL,

	NM_TITLE, (STRPTR)m_Checking, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)m_Test_archives, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Virus_check, NULL, NM_ITEMDISABLED, 0L, NULL,
	NM_ITEM, (STRPTR)NM_BARLABEL, NULL, 0, 0L, NULL,
	NM_ITEM, (STRPTR)m_Delete_move_not_installed_files, NULL, 0, 0L, NULL,
	NM_END, NULL, NULL, 0, 0L, NULL };

char e_Ok[20];
char e_Cancel[20];
char e_Name[20];
char e_Description[20];
char e_Info[20];

struct NewMenu EditNewMenu[] = {
	NM_TITLE, (STRPTR)m_Project, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)e_Ok, (STRPTR)"O", 0, 0L, NULL,
	NM_ITEM, (STRPTR)e_Cancel, (STRPTR)"C", 0, 0L, NULL,
	NM_TITLE, (STRPTR)m_Edit, NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)e_Name, (STRPTR)"N", NM_ITEMDISABLED, 0L, NULL,
	NM_ITEM, (STRPTR)e_Description, (STRPTR)"D", 0, 0L, NULL,
	NM_ITEM, (STRPTR)e_Info, (STRPTR)"I", 0, 0L, NULL,
	NM_END, NULL, NULL, 0, 0L, NULL };

UWORD FileEditorGTypes[] = {
	LISTVIEW_KIND,
	LISTVIEW_KIND
};

UWORD EditGTypes[] = {
	STRING_KIND,
	STRING_KIND,
	BUTTON_KIND,
	BUTTON_KIND,
	BUTTON_KIND
};

char g_File_directories[20];
char g_Files[20];

struct NewGadget FileEditorNGad[] = {
	19, 42, 267, 168, (UBYTE *)g_File_directories, NULL, GD_LIST_1, PLACETEXT_ABOVE|NG_HIGHLABEL, NULL, NULL,
	297, 42, 267, 168, (UBYTE *)g_Files, NULL, GD_LIST_2, PLACETEXT_ABOVE|NG_HIGHLABEL, NULL, NULL
};

char g_File_name[20];
char g_File_description[20];
char g_File_info[20];
char g_Remove_conf[20];
char g_Update_size[20];

struct NewGadget EditNGad[] = {
	10, 15, 165, 14, (UBYTE *)g_File_name, NULL, GD_FILE_NAME, PLACETEXT_ABOVE, NULL, NULL,
	179, 15, 309, 14, (UBYTE *)g_File_description, NULL, GD_COMMENT, PLACETEXT_ABOVE, NULL, NULL,
	10, 34, 97, 14, (UBYTE *)g_File_info, NULL, GD_FILEINFO, PLACETEXT_IN, NULL, NULL,
	374, 133, 122, 11, (UBYTE *)g_Remove_conf, NULL, GD_REMOVE_CONF, PLACETEXT_IN, NULL, NULL,
	374, 100, 122, 11, (UBYTE *)g_Update_size, NULL, GD_UPDATE_SIZE, PLACETEXT_IN, NULL, NULL
};

ULONG FileEditorGTags[] = {
	(GTLV_ShowSelected), NULL, (TAG_DONE),
	(GTLV_ShowSelected), NULL, (TAG_DONE)
};

ULONG EditGTags[] = {
	(GTST_MaxChars), 18, (GA_Disabled), TRUE, (TAG_DONE),
	(GTST_MaxChars), 36, (TAG_DONE),
	(TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE),
	(GA_Disabled), TRUE, (TAG_DONE)
};

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

int OpenFileEditorWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &FileEditorGList )))
		return( 1L );

	strcpy (g_File_directories, GLS (&txt_117));
	strcpy (g_Files, GLS (&txt_118));

	for( lc = 0, tc = 0; lc < FileEditor_CNT; lc++ ) {

		CopyMem((char * )&FileEditorNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		FileEditorGadgets[ lc ] = g = CreateGadgetA((ULONG)FileEditorGTypes[ lc ], g, &ng, ( struct TagItem * )&FileEditorGTags[ tc ] );

		while( FileEditorGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	strcpy (m_Project, GLS (&txt_085));
	strcpy (m_About, GLS (&txt_086));
	strcpy (m_Quit, GLS (&txt_087));
	strcpy (m_Directories, GLS (&txt_088));
	strcpy (m_New, GLS (&txt_089));
	strcpy (m_Change_name, GLS (&txt_090));
	strcpy (m_Change_path, GLS (&txt_091));
	strcpy (m_Delete, GLS (&txt_092));
	strcpy (m_Update, GLS (&txt_093));
	strcpy (m_File, GLS (&txt_094));
	strcpy (m_Auto_install, GLS (&txt_095));
	strcpy (m_Edit, GLS (&txt_096));
	strcpy (m_Update_file_sizes, GLS (&txt_097));
	strcpy (m_Count_files, GLS (&txt_098));
	strcpy (m_Update_preview_files, GLS (&txt_136));
	strcpy (m_Comments, GLS (&txt_099));
	strcpy (m_Auto_search, GLS (&txt_100));
	strcpy (m_From_file_list, GLS (&txt_101));
	strcpy (m_Checking, GLS (&txt_102));
	strcpy (m_Test_archives, GLS (&txt_103));
	strcpy (m_Virus_check, GLS (&txt_104));
	strcpy (m_Delete_move_not_installed_files, GLS (&txt_105));

	if ( ! ( FileEditorMenus = CreateMenus( FileEditorNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( FileEditorMenus, VisualInfo, GTMN_TextAttr, &topaz8, TAG_DONE );

	if ( ! ( FileEditorWnd = OpenWindowTags( NULL,
				WA_Left,	FileEditorLeft,
				WA_Top,		FileEditorTop,
				WA_Width,	FileEditorWidth,
				WA_Height,	FileEditorHeight + offy,
				WA_IDCMP,	LISTVIEWIDCMP|IDCMP_MENUPICK|IDCMP_CLOSEWINDOW|IDCMP_RAWKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	FileEditorGList,
				WA_Title,	FileEditorWdt,
				WA_PubScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( FileEditorWnd, FileEditorMenus );
	GT_RefreshWindow( FileEditorWnd, NULL );

	return( 0L );
}

void CloseFileEditorWindow( void )
{
	if ( FileEditorMenus      ) {
		ClearMenuStrip( FileEditorWnd );
		FreeMenus( FileEditorMenus );
		FileEditorMenus = NULL;	}

	if ( FileEditorWnd        ) {
		CloseWindow( FileEditorWnd );
		FileEditorWnd = NULL;
	}

	if ( FileEditorGList      ) {
		FreeGadgets( FileEditorGList );
		FileEditorGList = NULL;
	}
}

void EditRender( void )
{
	UWORD		offx, offy;

	offx = EditWnd->BorderLeft;
	offy = EditWnd->BorderTop;


	DrawBevelBox( EditWnd->RPort, offx + 10, offy + 89, 356, 57, GT_VisualInfo, VisualInfo, GTBB_Recessed, TRUE, TAG_DONE );
}

int OpenEditWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = Scr->WBorLeft, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( g = CreateContext( &EditGList )))
		return( 1L );

	strcpy (g_File_name, GLS (&txt_119));
	strcpy (g_File_description, GLS (&txt_120));
	strcpy (g_File_info, GLS (&txt_121));
	strcpy (g_Remove_conf, GLS (&txt_122));
	strcpy (g_Update_size, GLS (&txt_123));
	
	for( lc = 0, tc = 0; lc < Edit_CNT; lc++ ) {

		CopyMem((char * )&EditNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = &topaz8;
		ng.ng_LeftEdge  += offx;
		ng.ng_TopEdge   += offy;

		EditGadgets[ lc ] = g = CreateGadgetA((ULONG)EditGTypes[ lc ], g, &ng, ( struct TagItem * )&EditGTags[ tc ] );

		while( EditGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	strcpy (m_Project, GLS (&txt_085));
	strcpy (m_Edit, GLS (&txt_096));

	strcpy (e_Ok, GLS (&txt_OK));
	strcpy (e_Cancel, GLS (&txt_113));
	strcpy (e_Name, GLS (&txt_114));
	strcpy (e_Description, GLS (&txt_115));
	strcpy (e_Info, GLS (&txt_116));

	if ( ! ( EditMenus = CreateMenus( EditNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( EditMenus, VisualInfo, GTMN_TextAttr, &topaz8, TAG_DONE );

	if ( ! ( EditWnd = OpenWindowTags( NULL,
				WA_Left,	EditLeft,
				WA_Top,		EditTop,
				WA_Width,	EditWidth,
				WA_Height,	EditHeight + offy,
				WA_IDCMP,	STRINGIDCMP|BUTTONIDCMP|IDCMP_MENUPICK|IDCMP_CLOSEWINDOW|IDCMP_RAWKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_SIZEGADGET|WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	EditGList,
				WA_Title,	GLS (&txt_084),
				WA_PubScreen,	Scr,
				WA_MinWidth,	67,
				WA_MinHeight,	21,
				WA_MaxWidth,	724,
				WA_MaxHeight,	283,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( EditWnd, EditMenus );
	GT_RefreshWindow( EditWnd, NULL );

	EditRender();

	return( 0L );
}

void CloseEditWindow( void )
{
	if ( EditMenus      ) {
		ClearMenuStrip( EditWnd );
		FreeMenus( EditMenus );
		EditMenus = NULL;	}

	if ( EditWnd        ) {
		CloseWindow( EditWnd );
		EditWnd = NULL;
	}

	if ( EditGList      ) {
		FreeGadgets( EditGList );
		EditGList = NULL;
	}
}

